# Generated by Django 3.2.18 on 2023-11-21 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('addressId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('county', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('childIdD', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenHomes',
            fields=[
                ('childrenHomes', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('addressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.addresstable')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photoID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('blobLink', models.CharField(max_length=50)),
                ('photoDate', models.DateTimeField()),
                ('childPhotoID', models.ManyToManyField(to='database.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('childrenHomeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.addresstable')),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='lecturerModules',
        ),
        migrations.RemoveField(
            model_name='module',
            name='careers',
        ),
        migrations.RemoveField(
            model_name='modulepathway',
            name='moduleID',
        ),
        migrations.RemoveField(
            model_name='modulepathway',
            name='pathwayID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pathwayID',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModulePathway',
        ),
        migrations.DeleteModel(
            name='Pathway',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='staff',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='socialWorker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialWorker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
