# Generated by Django 3.2.23 on 2023-11-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20231121_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='childIdD',
            new_name='childID',
        ),
    ]
