# Generated by Django 3.2.23 on 2023-11-23 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_childidd_child_childid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresstable',
            old_name='addressLine1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='addresstable',
            old_name='addressLine2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='socialWorker',
            new_name='social_workerID',
        ),
        migrations.RenameField(
            model_name='childrenhomes',
            old_name='childrenHomes',
            new_name='children_homeID',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='blobLink',
            new_name='blob_link',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='childPhotoID',
            new_name='child_photoID',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='photoDate',
        ),
        migrations.AddField(
            model_name='childrenhomes',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childrenhomes',
            name='name',
            field=models.CharField(default='Home', max_length=50),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='photos',
            name='uploaderID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('entryID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=1000000)),
                ('entry_date', models.DateTimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
